"""add youtube embedded links column to movie data

Revision ID: 2a703b933e27
Revises: e7193ffa4dd6
Create Date: 2024-02-02 20:24:49.922644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a703b933e27'
down_revision = 'e7193ffa4dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedded_youtube_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('embedded_youtube_link')

    # ### end Alembic commands ###
