"""string to number duration and time stamp wh

Revision ID: 3829462749a6
Revises: e1b14a1b901f
Create Date: 2024-02-23 13:57:26.255927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3829462749a6'
down_revision = 'e1b14a1b901f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_duration', sa.Integer(), nullable=True))
        batch_op.alter_column('time_stamp',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_histories', schema=None) as batch_op:
        batch_op.alter_column('time_stamp',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('video_duration')
        batch_op.drop_column('movie_title')

    # ### end Alembic commands ###
