"""season_name to series_name

Revision ID: 3e402e4fa6b0
Revises: c74d09025b67
Create Date: 2024-02-15 15:48:49.236119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e402e4fa6b0'
down_revision = 'c74d09025b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_name', sa.String(), nullable=True))
        batch_op.drop_column('season_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('series_name')

    # ### end Alembic commands ###
