"""year of release changed to release date

Revision ID: 6edae3c21520
Revises: 3e402e4fa6b0
Create Date: 2024-02-22 12:23:18.956742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edae3c21520'
down_revision = '3e402e4fa6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(), nullable=True))
        batch_op.drop_column('year_of_release')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_release', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
