"""remove due to pre existing trailer column

Revision ID: 80616b6ab664
Revises: 2a703b933e27
Create Date: 2024-02-02 20:26:16.064107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80616b6ab664'
down_revision = '2a703b933e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('embedded_youtube_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedded_youtube_link', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
