"""foreign key for tv show episodes

Revision ID: a2c379ddde7a
Revises: 04f16d708cc5
Create Date: 2024-02-13 21:48:04.076489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c379ddde7a'
down_revision = '04f16d708cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_episodes_season_id_tv_seasons'), 'tv_seasons', ['season_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_episodes_season_id_tv_seasons'), type_='foreignkey')
        batch_op.drop_column('season_id')

    # ### end Alembic commands ###
