"""year of release changed to release date for series

Revision ID: c82c51e206ff
Revises: 6edae3c21520
Create Date: 2024-02-22 13:04:15.222877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82c51e206ff'
down_revision = '6edae3c21520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(), nullable=True))
        batch_op.drop_column('year_of_release')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_release', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
