"""watch history table creation

Revision ID: e1b14a1b901f
Revises: c82c51e206ff
Create Date: 2024-02-23 13:35:43.897314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b14a1b901f'
down_revision = 'c82c51e206ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.String(), nullable=True),
    sa.Column('episode_number', sa.String(), nullable=True),
    sa.Column('episode_name', sa.String(), nullable=True),
    sa.Column('season_number', sa.String(), nullable=True),
    sa.Column('series_name', sa.String(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tv_series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_watch_histories_movie_id_movies')),
    sa.ForeignKeyConstraint(['tv_series_id'], ['tv_series.id'], name=op.f('fk_watch_histories_tv_series_id_tv_series')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watch_histories_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_histories')
    # ### end Alembic commands ###
