"""create tv series table

Revision ID: e7193ffa4dd6
Revises: 32dfbb946aac
Create Date: 2024-01-08 19:45:51.330312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7193ffa4dd6'
down_revision = '32dfbb946aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('writer', sa.String(), nullable=True),
    sa.Column('year_of_release', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('motion_picture_rating', sa.String(), nullable=True),
    sa.Column('trailer', sa.String(), nullable=True),
    sa.Column('seasons', sa.String(), nullable=True),
    sa.Column('episode_count', sa.String(), nullable=True),
    sa.Column('average_episode_time', sa.String(), nullable=True),
    sa.Column('is_airing', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('num_of_clicks', sa.Integer(), nullable=True),
    sa.Column('stars', sa.String(), nullable=True),
    sa.Column('all_cast_and_crew', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tv_series_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_favorites_tv_series_id_tv_series'), 'tv_series', ['tv_series_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_favorites_tv_series_id_tv_series'), type_='foreignkey')
        batch_op.drop_column('tv_series_id')

    op.drop_table('tv_series')
    # ### end Alembic commands ###
